api/urls.py
from .views import ArticleViewSet
from django.urls import path, include
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register(r'articles', ArticleViewSet)

urlpatterns = [
    path('', include(router.urls)),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'  

urlpatterns = [
    path('', views.article_index ,name='home'),
    path('<slug:slug>', views.article_detail, name='detail'),
    path('like/<slug:slug>', views.article_like, name='like_article'),
]

weblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('api/', include('api.urls')),
    path('blog/', include('blog.urls')),
    path('account/', include('account.urls')),
    path('resume/', include('resume.urls')),
    path('contact_us/', include('contact_us.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse




class Article(models.Model):
    title = models.CharField(max_length = 100, unique = True)
    body = models.TextField()
    slug = models.SlugField(null=True)
    image = models.ImageField(default='default.jpg', blank=True)
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    likes = models.ManyToManyField(User, related_name='blog_posts')


    def __str__(self) -> str:
        return self.title

    def snippet(self):
        return self.body[:100]
    
    def get_absolute_url(self):
        return reverse("blog:detail", kwargs={"slug": self.slug})

    def total_likes(self):
        return self.likes.count()



class Comment(models.Model):
    article = models.ForeignKey(Article, related_name='comments', on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)

    class Meta:
        ordering = ['created_on']


    def __str__(self) -> str:
        return f'Comment {self.body} by {self.name}'

blog/forms.py
from django import forms
from django.db.models.base import Model
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'body')

blog/views.py
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from blog.forms import CommentForm
from django.http import HttpResponseRedirect
from .models import Article


def article_like(request, slug):
    post = get_object_or_404(Article, slug=slug)
    post.likes.add(request.user)
    return HttpResponseRedirect(reverse('blog:detail', kwargs={'slug':slug}))


def article_index(request):
    articles = Article.objects.all().order_by('-pub_date')
    context = {'articles': articles}
    return render(request, 'blog/article_index.html', context)



def article_detail(request, slug):
    this_article = get_object_or_404(Article, slug=slug)
    total_likes = this_article.total_likes()
    comments = this_article.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.article = this_article
            new_comment.save()
    
    else:
        comment_form = CommentForm()

    return render(request, 'blog/article_detail.html', context={  
                                                                'this_article': this_article,
                                                                'comments':comments, 
                                                                'new_comment':new_comment, 
                                                                'comment_form':comment_form,
                                                                'total_likes': total_likes,
                                                                }
)

blog/templates/blog/article_detail.html
{% extends 'base.html' %}
{% load static %}


{% block tab_title %}
<title>{{this_article.title}}</title>
{% endblock tab_title %}


{% block static_files %}  
<link rel="stylesheet" href="{% static 'blog/style.css' %}">
{% endblock static_files %}  


{% block page_content %}      

	<br>
	<br>
	<h3>{{ this_article.title }}</h3>
	<p>{{ this_article.body|safe}}</p><hr>
	<img src="{{this_article.image.url}}" class="img-fluid"/>
	<br>
	<div>
	<small>Created: {{ this_article.pub_date|timesince}}</small><hr>
	<small>Author: {{ this_article.author|title }}</small><hr>
	</div>

  <br>
  <form action="{% url 'blog:like_article' this_article.slug %}"
  method="POST">
      {% csrf_token %}
      <button type="submit" value="{{ this_article.slug }}" class="btn btn-primary btn-sm">Like</button>
      - {{total_likes}} Likes
  </form>
  <br>


{% load crispy_forms_tags %}

    <div class="col-md-8 card mb-4  mt-3 ">
      <div class="card-body">
        <!-- comments -->
        <h2>{{ comments.count }} comments</h2>

        {% for comment in comments %}
        <div class="comments" style="padding: 10px;">
          <p class="font-weight-bold">
            {{ comment.name }}
            <span class=" text-muted font-weight-normal">
              {{ comment.created_on }}
            </span>
          </p>
          {{ comment.body | linebreaks }}
        </div>
        {% endfor %}
      </div>
    </div>
    <div class="col-md-8 card mb-4  mt-3 ">
      <div class="card-body">
        {% if new_comment %}
        <div class="alert alert-success" role="alert">
          Your comment is awaiting moderation
        </div>
        {% else %}
        <h3>Leave a comment</h3>
        <form method="post" style="margin-top: 1.3em;">
          {{ comment_form | crispy }}
          {% csrf_token %}
          <button type="submit" class="btn btn-primary  btn-lg">Submit</button>
        </form>
        {% endif %}
      </div>
    </div>
  </div>



{% endblock page_content %}
 

blog/templates/blog/article_index.html
{% extends "base.html" %}
{% load static %}

{% block tab_title %}
<title>Mosihere Blog</title>
{% endblock tab_title %}


{% block static_files %} 
<link rel="stylesheet" href="{% static 'blog/style.css' %}">

{% endblock static_files %}


{% block page_content %}

{% if user.is_authenticated %}
<h3><center>Welcome Back "{{user.get_username}}" </center></h3>
{% endif %}

<h1>Articles</h1>

<div class="row">
{% for article in articles %}
    <div class="col-md-4">
        <div class="card mb-2">

            <div class="card-deck">
  <div class="card">
    <img src="{{article.image.url}}" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">{{article.title}}</h5>
      <p class="card-text">{{article.snippet|truncatewords:'10'}}</p>
      <p class="card-text"><small class="text-muted">Date Published: {{article.pub_date|date:"d M Y"}}</small></p>
    </div>
    
  </div>
</div>
                <a href="{{ article.get_absolute_url }}"
                   class="btn btn-primary">
                    Read More
                </a>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}



<div class="card-deck">
  <div class="card">
    <img src="{{article.image.url}}" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">{{article.title}}</h5>
      <p class="card-text">{{article.snippet}}</p>
      <p class="card-text"><small class="text-muted">{{this_article.pub_date}}</small></p>
    </div>
    
  </div>
</div>