account/urls.py
from django.urls import path
from . import views


app_name = 'account'

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.user_register, name='register'),

]

api/urls.py
from .views import ArticleViewSet
from django.urls import path, include
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register(r'articles', ArticleViewSet)

urlpatterns = [
    path('', include(router.urls)),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'  

urlpatterns = [
    path('', views.article_index ,name='home'),
    path('<slug:slug>', views.article_detail, name='detail'),
    path('like/<slug:slug>', views.article_like, name='like_article'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.homeview, name='home-page'),
]

resume/urls.py
from django.urls import path
from . import views


app_name = 'resume'

urlpatterns = [
    path('', views.main_page, name='home')
]

weblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('api/', include('api.urls')),
    path('blog/', include('blog.urls')),
    path('account/', include('account.urls')),
    path('resume/', include('resume.urls')),
    path('contact_us/', include('contact_us.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  {% block tab_title %}
  <title>Mosihere Home</title>
  {% endblock tab_title %}

</head>

<body>

{% block static_files %} {% endblock static_files %}



<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="{% url 'home:home-page' %}">Home</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <li class="nav-item" color='red'>
                <a class="nav-link" href="{% url 'resume:home' %}">Resume</a>
              </li>
              <a class="nav-link" href="{% url 'contact_us:contact' %}">Contact Me</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'blog:home' %}">Blog</a>
            </li>


            <li class="nav-item">
              <a class="nav-link" href="{% url 'account:login' %}">Login</a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'account:register' %}">Signup</a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'account:logout' %}">Logout</a>
            </li>


          </ul>
        </div>
    </div>

</nav>

<div class="container">


        {% block page_content %}{% endblock page_content %}
</div>





<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<!-- Popper JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>